apiVersion: "operators.coreos.com/v1alpha1"
kind: "CatalogSource"
metadata:
  name: "certified-operators"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/certified-operator-index:v4.7
  displayName: "Certified Operators"
  publisher: "Red Hat"
  priority: -200
  updateStrategy:
    registryPoll:
      interval: 10m
